# Generated by Django 4.0.3 on 2022-04-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_active',
            new_name='activation',
        ),
    ]
